### ISSUE TITLE
catkin build CUDNN Problem

### ISSUE THREAD

**Issue by jaronski** [Hiroaki-K4/tkdnn_ros#1]
checked with nvidia SDK Manager that CUDNN 8 and TensorRT 7.1 is installed on my Xavier AGX. Also tried to find CUDNNConfig.cmake and cudnn-config.cmake on Xavier AGX. 

CMake Error at /home/nvidia/catkin_tkDnn/src/tkdnn_ros/tkdnn_ros/CMakeLists.txt:23 (find_package):
  By not providing "FindCUDNN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUDNN", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUDNN" with any of
  the following names:

    CUDNNConfig.cmake
    cudnn-config.cmake

  Add the installation prefix of "CUDNN" to CMAKE_PREFIX_PATH or set
  "CUDNN_DIR" to a directory containing one of the above files.  If "CUDNN"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by Hiroaki-K4** [comment]
Have you ever tried running tkDNN alone? The environment recommended by tkDNN is CUDNN 7.6, TENSORRT 6.01, so that may be relevant. tkdnn_ros is also tested in the same environment.

**Comment by Hiroaki-K4** [comment]
Have you ever run tkDNN alone? This CMakeList is basically the same as tkDNN.

**Comment by jaronski** [comment]
yes tkDNN alone works for me

**Comment by godhj93** [comment]
@jaronski  How did you solve the problem? i have same issues in docker environment(tkDNN docker).

```
CMake Error at tkdnn_ros/tkdnn_ros/CMakeLists.txt:23 (find_package):
  By not providing "FindCUDNN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUDNN", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUDNN" with any of
  the following names:

    CUDNNConfig.cmake
    cudnn-config.cmake

  Add the installation prefix of "CUDNN" to CMAKE_PREFIX_PATH or set
  "CUDNN_DIR" to a directory containing one of the above files.  If "CUDNN"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
root@6d178096ada9:/catkin_ws# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
root@6d178096ada9:/catkin_ws# https://github.com/Hiroaki-K4/tkdnn_ros.git
bash: https://github.com/Hiroaki-K4/tkdnn_ros.git: No such file or directory
root@6d178096ada9:/catkin_ws# 
root@6d178096ada9:/catkin_ws# cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
cat: /usr/local/cuda/include/cudnn.h: No such file or directory
root@6d178096ada9:/catkin_ws# cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

```
