### ISSUE TITLE
[tkdnn_ros-2] process has died

### ISSUE THREAD

**Issue by hasanzfdn** [Hiroaki-K4/tkdnn_ros#2]
when I run this command (roslaunch tkdnn_ros tkdnn_ros.launch)
Im getting this error: 
  
started roslaunch server http://aesk-TULPAR-T7-V19-4:35321/

SUMMARY
PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /yolo_model/detection_classes/value: 18
 * /yolo_model/threshold/value: 0.5
 * /yolo_model/video_file/name: /home/aesk/otonom...
 * /yolo_model/weights_file/name: /home/aesk/yolov4...

NODES
  /
    tkdnn_ros (tkdnn_ros/tkdnn_ros)

auto-starting new master
process[master]: started with pid [10236]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7c92e160-fc33-11eb-a11c-c809a83589c3
process[rosout-1]: started with pid [10261]
started core service [/rosout]
process[tkdnn_ros-2]: started with pid [10268]
[tkdnn_ros-2] process has died [pid 10268, exit code -11, cmd /home/aesk/yolov4_in_other_framework/catkin_ws/devel/lib/tkdnn_ros/tkdnn_ros __name:=tkdnn_ros __log:=/home/aesk/.ros/log/7c92e160-fc33-11eb-a11c-c809a83589c3/tkdnn_ros-2.log].
log file: /home/aesk/.ros/log/7c92e160-fc33-11eb-a11c-c809a83589c3/tkdnn_ros-2*.log

 ### I m not sure if ım installed correctly tkdnn ros repository.  Can u tell me how can I install this repository  correctly and clearly

**Comment by lilyildiz** [comment]
I had the same problem, the issue was because my camera topic was not being published and my OPENCV_DIR path was wrong. Also make sure you have OPENCV 4 and TensorRT 7 installed.

For info, before solving these issues i had OPENCV 3 and TensorRT 6.

**Comment by hasanzfdn** [comment]
I already solved this issue last year. But thank you very much Mr.Lil
